spring:
  application:
    name: notification-service
    #    RABBITMQ
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
server:
  port: 8082

logging:
  level:
    org: ERROR
