spring:
  application:
    name: notification-service
    #    RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8083

rabbitmq:
  notifications:
    queue: notifications-queue
    group: notifications-group
    routing_key: notifications.key123
    exchange_name: notifications-exchange

logging:
  level:
    pl:
      alex: DEBUG
