spring:
  application:
    name: notification-service
    #    RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8083

rabbitmq:
  user:
    group: users-group
    exchange: user.exchange
    all:
      queue: user.all.queue
      key: user.*
    dlt:
      queue: user.dlt.queue
      exchange: user.dlt.exchange
      key: user.dlt
      ttl: 5000

logging:
  level:
    pl:
      alex: DEBUG
