spring:
  application:
    name: notification-service
    #    RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082

rabbitmq:
  users:
    group: users-group
    exchange: users.exchange
    all:
      queue: users.all.queue
      routing_key: users.*

logging:
  level:
    pl:
      alex: DEBUG
