spring:
  application:
    name: users-service
  #    RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8081

rabbitmq:
  users:
    group: users-group
    exchange: users.exchange
    created:
      routing_key: users.created

logging:
  level:
    pl:
      alex: DEBUG
